### ISSUE TITLE
Creación Panel Retos Detalle

### ISSUE THREAD

**Issue by JaviShyruk** [lmonterogarcia/BestipesCook-Escritorio#26]
**Tareas que realizar :**

- [x] Titulo(Label)
- [x] Fecha(Label)
- [x] Tiempo del reto(Label)
- [x] Descripción (Label)
- [x] Guardar(Button)
- [x] Cancelar(Button)
- [x] img
- [x] Botones de edición

**Referencia :**

![Detalle_Retos_Mockup](https://user-images.githubusercontent.com/77279242/146540595-ac7c0344-64a1-4064-bc48-26c2dc8942e5.png)

**Comment by Manucv20** [comment]
Terminado
